#!/usr/bin/env bash
# Writes _config.local.yml (gitignored -- see Makefile's jekyll-serve comment, this
# is the file it already documents as "optional _config.local.yml override for local
# settings") from local .env values that must never be committed to the repo --
# currently just GOOGLE_CLIENT_ID (see .env.example and the comment on
# google_client_id in _config.yml). Mirrors the same idea
# .github/workflows/jekyll-gh-pages.yml uses for CI (its own _config.override.yml,
# generated fresh each run there), just sourced from a local .env instead of a
# repository secret. Safe to run even with no .env present: writes a file with
# google_client_id left unset, and Jekyll serves fine without it (the Google sign-in
# button just won't render).
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."

if [ -f .env ]; then
    set -a
    # shellcheck disable=SC1091
    source .env
    set +a
fi

{
    echo "# Auto-generated by scripts/generate_local_config_override.sh -- do not edit"
    echo "# or commit; re-run this script (or just start-dev.sh) after editing .env."
    if [ -n "${GOOGLE_CLIENT_ID:-}" ]; then
        echo "google_client_id: \"${GOOGLE_CLIENT_ID}\""
    fi
} > _config.local.yml
